apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 5
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: mcavage/demo-frontend:${WERCKER_GIT_BRANCH}-${WERCKER_GIT_COMMIT}
        ports:
        - containerPort: 8080